name: CI

on:
  pull_request:
    branches:
      - master
    tags-ignore:
      - '*'
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: olafurpg/setup-scala@v7
        with:
          java-version: graalvm-ce-java11@20.1.0
      - name: Install native-image
        run: gu install native-image
      - name: Print versions
        run: |
          java -version
          native-image --version
      - name: Run tests
        run:  sbt workflow/clean coverage workflow/test workflow/coverageReport
      - name: Publish coverage results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./workflow/target/scala-2.13/scoverage-report/scoverage.xml
          fail_ci_if_error: true
      - name: Package
        run: sbt workflow/clean workflow/alfredWorkflowPackage
      - name: Save the workflow as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: Jenkins.alfredworkflow
          path: workflow/target/alfred/Jenkins.alfredworkflow
