name: CI

on:
  pull_request:
    branches:
      - master
    tags-ignore:
      - '*'
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm-ce-java11@20.1.0
      - name: Install native-image
        run: gu install native-image
      - name: Print versions
        run: |
          java -version
          native-image --version
      - name: Formatting check
        run: sbt fmt-check
      - name: Run tests
        run:  sbt run-tests
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          projectBaseDir: workflow
#          args: >
#            -Dsonar.host.url=https://sonarcloud.io \
#            -Dsonar.projectKey=eli-jordan_alfred-jenkins \
#            -Dsonar.organization=eli-jordan \
#            -Dsonar.scala.coverage.reportPaths=./workflow/target/scala-2.13/scoverage-report/scoverage.xml
#            -Dsonar.junit.reportPaths=./workflow/target/test-reports/*.xml
      - name: SonarCloud Reporting
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.projectKey=eli-jordan_alfred-jenkins \
              -Dsonar.organization=eli-jordan \
              -Dsonar.scala.coverage.reportPaths=target/scala-2.13/scoverage-report/scoverage.xml \
              -Dsonar.junit.reportPaths=target/test-reports/*.xml \
              -Dsonar.verbose=true \
              workflow/sonarScan
      - name: Publish coverage results
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./workflow/target/scala-2.13/scoverage-report/scoverage.xml
          fail_ci_if_error: true
      - name: Package
        run: sbt run-package
      - name: Save the workflow as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: Jenkins.alfredworkflow
          path: workflow/target/alfred/Jenkins.alfredworkflow
